# For more information on how to manage conda environments from an environment.yml file, refer to
# https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
# https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually

name: graphrag
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - boto3
    - graphrag
    - litellm[proxy]